services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  

  web:
    build: .
    expose:
      - "5000" 
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  proxy:
    image: parth21699/notes-proxy:v1 
    ports:
      - "80:80"  
    depends_on:
      - web
